apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "linkvault.postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
      protocol: TCP
      name: postgres
  selector:
    {{- include "linkvault.postgresql.selectorLabels" . | nindent 4 }}
